In [2]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [3]:
np.__version__

'1.18.5'

In [2]:
arr1 = np.array([40,15,51,648,16,165,1684,68,265])
arr1
type(arr1)

numpy.ndarray

In [11]:
arr2 = np.array((40,15,51,648,16,165,68,26))
arr2

array([ 40,  15,  51, 648,  16, 165,  68,  26])

In [19]:
# nested lists result in multidimensional arrays
# inner lists are treated as rows of the resulting two-dimensional array
y=np.array([range(i,i+5) for i in [2,4,6]])
y

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [13]:
num1=np.array([[[12,5,64,6],[2,54,67,2]],[[45,5,56,50],[40,45,78,13]]])
num1
type(num1)

numpy.ndarray

In [4]:
# creating arrays filled with '0'
zero = np.zeros((10,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# Create a 3x5 floating-point array filled with 1s
ones = np.ones((3,5))
ones
# # Create a 3x5 array filled with 3.14
ones = np.full((3,5),3.14)
ones

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [2]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim) 
print(d.ndim)

0
1
2
3


In [14]:
b

array([1, 2, 3, 4])

In [5]:
# print 2 & 3 element in 
print((b[1]),(b[3]))

2 4


In [19]:
print(np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]]))

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [41]:
print(c[1,1])

5


In [8]:
xa=np.array([[[5,6,4],[7,6,4]],[[7,5,2],[7,5,4]]])
xa

array([[[5, 6, 4],
        [7, 6, 4]],

       [[7, 5, 2],
        [7, 5, 4]]])

In [14]:
print(xa[1,1,2]) # accesing the 3rd element of the 2nd array of the 1st array

4


In [39]:
 # Create an array filled with a linear sequence
 # Starting at 0, ending at 20, stepping by 2
 # (this is similar to the built-in range() function)
seq = np.arange(0,21,2)    
seq

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
 # Create an array of five values evenly spaced between 0 and 1
even = np.linspace(0,1,5)
even

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
# to know the datatype
arr2 = np.array([1,2,5,88,4])
arr2
print(arr2.dtype)

int32


In [3]:
# Change an element(index) of the array
num3 = np.array([1,2,3,5,2,5,15,4,84,84,849,85])
num3

array([  1,   2,   3,   5,   2,   5,  15,   4,  84,  84, 849,  85])

In [5]:
num3[1] = 9
num3

array([  1,   9,   3,   5,   2,   5,  15,   4,  84,  84, 849,  85])

In [6]:
num3[0:5]

array([1, 9, 3, 5, 2])

In [13]:
num3[ ::]

array([  1,   9,   3,   5,   2,   5,  15,   4,  84,  84, 849,  85])

In [22]:
# create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# create a vector
v = np.array([1, 0, 1])
v

array([1, 0, 1])

In [24]:
# create an empty matrix with the same shape as a
b = np.empty_like(a)
b

array([[  988,     0,   411],
       [32760,   992,     0],
       [  411,    -1,  1012]])

In [36]:
 # Create a 3x3 array of uniformly distributed
 # random values between 0 and 1   
rnd = np.random.random((3,3))
rnd

array([[0.20149308, 0.95190735, 0.72363999],
       [0.73261118, 0.74536935, 0.54610035],
       [0.41175354, 0.86138742, 0.11904265]])

In [46]:
 # Create a 3x3 array of normally distributed random values
 # with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.5452264 ,  1.28295816, -0.17960608],
       [ 0.3598367 , -0.0217608 , -0.26529572],
       [ 1.12301491,  0.87649135,  0.33488404]])

In [52]:
np.random.randint(10,99,(5,8))

array([[70, 26, 77, 92, 67, 32, 56, 20],
       [88, 57, 93, 45, 96, 32, 69, 31],
       [18, 32, 79, 66, 86, 87, 78, 62],
       [72, 28, 68, 82, 19, 27, 94, 29],
       [21, 61, 22, 18, 30, 44, 47, 81]])

In [5]:
res = np.arange(1,10).reshape((3,3))
res

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
res.reshape((3, 3)) # another way to reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
# concatenate array
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [67]:
# concatenate the 2-d array
z = np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.concatenate(z,axis=0)

array([1, 2, 3, 4, 5, 6])

In [71]:
print(z.ndim)

2


In [73]:
np.concatenate(xa,axis=1)  # concatenate along the second axis (zero-indexed)

array([[5, 6, 4, 7, 5, 2],
       [7, 6, 4, 7, 5, 4]])

In [76]:
num3.reshape((12,1))

array([[  1],
       [  9],
       [  3],
       [  5],
       [  2],
       [  5],
       [ 15],
       [  4],
       [ 84],
       [ 84],
       [849],
       [ 85]])

In [4]:
# Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2,x3 = np.split(x, [1,2])
print(x1, x2, x3)

[1] [2] [ 3 99 99  3  2  1]


In [17]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [8]:
lr = np.hsplit(grid,[2])
lr

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [2]:
zz = np.arange(1,10)
zz

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
zz.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
zz.shape

(9,)

In [15]:
n=np.arange(1,6)
n
np.add.reduce(n)

15

In [7]:
np.arange(3)[ :, np.newaxis]

array([[0],
       [1],
       [2]])

In [3]:
zz.shape

(9,)

In [10]:
s = 'ahjbsbobobnvsjajitajit'
numbob = 0

In [13]:
numbob = 0

for num in range(len(s) - 2):
    if s[num] == 'b':
        if s[num + 1] == 'o':
            if s[num + 2] == 'b':
                numbob += 1
                
print("Number of times bob occurs is: " + str(numbob))

Number of times bob occurs is: 2


In [24]:
s = 'ahjbsbobobnvsjajitajit'
no = 0
for num in range(len(s) - 3):
    if (s[num] + s[num + 1] + s[num + 2] + s[num + 3] ) == 'ajit':
        no += 1
        
print("Number of times ajit occurs is: " + str(no))

Number of times ajit occurs is: 2
